#define SPI_PIN_SCLK GPIO_NUM_13
#define SPI_PIN_MOSI GPIO_NUM_14

#define DISPLAY_SPI_SPEED SPI_MASTER_FREQ_20M
#define DISPLAY_PIN_CS GPIO_NUM_15
#define DISPLAY_PIN_RST GPIO_NUM_26
#define DISPLAY_PIN_DC GPIO_NUM_27
#define DISPLAY_PIN_BUSY GPIO_NUM_25
